---
abstract: 'Recursively merge two or more hashes, simply'
author:
  - 'Robert Krimen <robertkrimen@gmail.com>'
build_requires:
  Test::Deep: 0
  Test::Most: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
generated_by: 'Dist::Zilla version 2.101170'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Hash-Merge-Simple
recommends: {}
requires:
  Clone: 0
  Storable: 0
version: 0.05
