---
abstract: 'Recursively merge two or more hashes, simply'
author:
  - 'Robert Krimen, C<< <rkrimen at cpan.org> >>'
build_requires:
  Test::Deep: 0
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.710'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Hash-Merge-Simple
no_index:
  directory:
    - inc
    - t
version: 0.02
